# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-18 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyTitle', models.CharField(max_length=25)),
                ('created_at', models.CharField(max_length=25)),
                ('firstSentence', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=25)),
                ('auther', models.CharField(max_length=25)),
                ('post_id', models.IntegerField(default=0)),
                ('story_id', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
