# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-18 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyteller_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_day',
            field=models.CharField(default=11, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='created_mon',
            field=models.CharField(default=11, max_length=25),
            preserve_default=False,
        ),
    ]
