# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyteller_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follow_created_id',
            field=models.CharField(default=22, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='follow_likes',
            field=models.IntegerField(default=0),
        ),
    ]
