# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyteller_app', '0005_auto_20161219_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='firstSentence',
            field=models.CharField(max_length=100),
        ),
    ]
