# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyteller_app', '0007_auto_20161220_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_id',
            field=models.CharField(default=20, max_length=25),
            preserve_default=False,
        ),
    ]
