# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-23 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyteller_app', '0008_post_created_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
