# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-25 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyteller_app', '0009_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_auther',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
